// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiFlagrancia.Utilidades;

namespace apiFlagrancia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220617212746_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiFlagrancia.Entidades.DFlagrancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dependencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FecRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idFlagrancia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idFlagrancia");

                    b.ToTable("DFlagrancias");
                });

            modelBuilder.Entity("apiFlagrancia.Entidades.Dependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dependencias");
                });

            modelBuilder.Entity("apiFlagrancia.Entidades.Flagrancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acusacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audiencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoFlagrante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FecRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sentencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentenciaDET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacionJuridica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoArresto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flagrancias");
                });

            modelBuilder.Entity("apiFlagrancia.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("dependenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dependenciaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("apiFlagrancia.Entidades.DFlagrancia", b =>
                {
                    b.HasOne("apiFlagrancia.Entidades.Flagrancia", "flagrancia")
                        .WithMany()
                        .HasForeignKey("idFlagrancia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flagrancia");
                });

            modelBuilder.Entity("apiFlagrancia.Entidades.Usuario", b =>
                {
                    b.HasOne("apiFlagrancia.Entidades.Dependencia", "dependencia")
                        .WithMany()
                        .HasForeignKey("dependenciaId");

                    b.Navigation("dependencia");
                });
#pragma warning restore 612, 618
        }
    }
}
